# Generated by Django 6.1.1 on 2026-09-25 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=120, verbose_name='nombre científico')),
                ('forma_conteo', models.CharField(choices=[('estrella', 'Estrella — hojas que salen de un centro (plátano, palma)'), ('copa', 'Copa — mancha redonda (cítricos, cacao, frutales)')], max_length=10, verbose_name='forma de conteo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.CharField(default='Arauca', max_length=80)),
                ('municipio', models.CharField(default='Saravena', max_length=80)),
                ('vereda', models.CharField(blank=True, max_length=120)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='área total (ha)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('dispositivo', models.CharField(blank=True, help_text='Modelo del dron o cámara.', max_length=120)),
                ('altura_vuelo_m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='altura de vuelo (m)')),
                ('gsd_cm_px', models.DecimalField(blank=True, decimal_places=2, help_text='Cuántos centímetros del terreno cubre un píxel. Permite pasar a plantas por hectárea.', max_digits=6, null=True, verbose_name='resolución en el suelo (cm/px)')),
                ('condiciones', models.CharField(blank=True, choices=[('soleado', 'Soleado'), ('nublado', 'Nublado'), ('parcial', 'Parcialmente nublado'), ('lluvia', 'Lluvia reciente')], max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(height_field='alto_px', upload_to='fotos/%Y/%m/', width_field='ancho_px')),
                ('ancho_px', models.PositiveIntegerField(editable=False, null=True)),
                ('alto_px', models.PositiveIntegerField(editable=False, null=True)),
                ('subida', models.DateTimeField(auto_now_add=True)),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='campo.captura')),
            ],
            options={
                'ordering': ['-subida'],
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(default='centros', max_length=20, verbose_name='método')),
                ('forma', models.CharField(choices=[('estrella', 'Estrella — hojas que salen de un centro (plátano, palma)'), ('copa', 'Copa — mancha redonda (cítricos, cacao, frutales)')], max_length=10)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='versión del método')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('confianza', models.CharField(blank=True, choices=[('consistente', 'Consistente'), ('rango', 'Rango — el conteo depende del ajuste'), ('vacio', 'Sin plantas detectadas')], max_length=12)),
                ('conteo', models.PositiveIntegerField(blank=True, null=True)),
                ('conteo_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='conteo mínimo')),
                ('conteo_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='conteo máximo')),
                ('escala_px', models.PositiveIntegerField(blank=True, null=True, verbose_name='distancia entre plantas (px)')),
                ('mensaje', models.TextField(blank=True)),
                ('ejecutado', models.DateTimeField(auto_now_add=True)),
                ('duracion_s', models.FloatField(blank=True, null=True, verbose_name='duración (s)')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='campo.foto')),
            ],
            options={
                'verbose_name': 'análisis',
                'verbose_name_plural': 'análisis',
                'ordering': ['-ejecutado'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o código del lote en la finca.', max_length=80)),
                ('variedad', models.CharField(blank=True, max_length=80)),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='área (ha)')),
                ('fecha_siembra', models.DateField(blank=True, null=True, verbose_name='fecha de siembra')),
                ('distancia_plantas_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='distancia entre plantas (m)')),
                ('distancia_surcos_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='distancia entre surcos (m)')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='campo.cultivo')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='campo.finca')),
            ],
            options={
                'ordering': ['finca', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='captura',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='campo.lote'),
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de la planta dentro del análisis.')),
                ('x_px', models.FloatField()),
                ('y_px', models.FloatField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('revisar', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='campo.analisis')),
            ],
            options={
                'ordering': ['analisis', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='documento de identidad')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('autoriza_datos', models.BooleanField(default=False, help_text='Consentimiento para registrar y tratar sus datos personales.', verbose_name='autoriza el tratamiento de datos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Cuenta del sistema, si el productor entra directamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'productores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fincas', to='campo.productor'),
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='campo.planta')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='campo.variable')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('finca', 'nombre'), name='lote_unico_por_finca'),
        ),
        migrations.AddConstraint(
            model_name='planta',
            constraint=models.UniqueConstraint(fields=('analisis', 'numero'), name='planta_unica_por_analisis'),
        ),
        migrations.AddConstraint(
            model_name='finca',
            constraint=models.UniqueConstraint(fields=('productor', 'nombre'), name='finca_unica_por_productor'),
        ),
        migrations.AddConstraint(
            model_name='medicion',
            constraint=models.UniqueConstraint(fields=('planta', 'variable'), name='una_medicion_por_variable'),
        ),
    ]
