# Generated by Django 5.2.17 on 2026-10-05 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60, unique=True)),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Posición en la pantalla de ventas (menor primero).",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "telefono",
                    models.CharField(blank=True, max_length=30, verbose_name="teléfono"),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Mesa 4, Barra, Terraza 2.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Consecutivo, se asigna al cobrar.",
                        null=True,
                        unique=True,
                        verbose_name="número",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="abierta",
                        max_length=10,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("tarjeta", "Tarjeta"),
                        ],
                        max_length=15,
                    ),
                ),
                ("abierta_en", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cerrada_en",
                    models.DateTimeField(
                        blank=True, help_text="Cuándo se cobró o se anuló.", null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = cliente anónimo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="barra.cliente",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="barra.mesa",
                    ),
                ),
            ],
            options={
                "ordering": ["-abierta_en"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.PositiveIntegerField(verbose_name="precio de venta")),
                (
                    "costo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lo que te cuesta una unidad.",
                        verbose_name="costo de compra",
                    ),
                ),
                (
                    "controla_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Desmárcalo para cócteles, comida preparada u otros que no cuentas por unidad.",
                        verbose_name="controla inventario",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        help_text="Se actualiza solo con las ventas. Para compras y conteos usa Inventario.",
                        verbose_name="unidades disponibles",
                    ),
                ),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = sin aviso.",
                        verbose_name="avisar cuando queden",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmárcalo para ocultarlo de ventas sin perder su historial.",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="barra.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["categoria__orden", "categoria__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[("compra", "Compra"), ("ajuste", "Conteo físico")],
                        max_length=10,
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(help_text="Positivo = entra, negativo = sale."),
                ),
                ("costo_unitario", models.PositiveIntegerField(blank=True, null=True)),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="barra.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Linea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio",
                    models.PositiveIntegerField(
                        help_text="Copia del precio al pedir.",
                        verbose_name="precio unitario",
                    ),
                ),
                (
                    "costo",
                    models.PositiveIntegerField(
                        help_text="Copia del costo al pedir.",
                        verbose_name="costo unitario",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="barra.factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas",
                        to="barra.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="factura",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "abierta")),
                fields=("mesa",),
                name="una_factura_abierta_por_mesa",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nombre"), name="producto_unico_en_categoria"
            ),
        ),
        migrations.AddConstraint(
            model_name="linea",
            constraint=models.UniqueConstraint(
                fields=("factura", "producto"), name="una_linea_por_producto"
            ),
        ),
    ]
